import React, { useState, useRef, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { useSwarmStore, Report } from '../stores/swarmStore';

type TabType = 'live' | 'archive' | 'settings';

interface LogEntry {
    id: string;
    level: 'info' | 'warning' | 'critical' | 'processing';
    message: string;
    timestamp: number;
}

export const AutoReportPanel: React.FC = () => {
    const { reports, addReport } = useSwarmStore();
    const [activeTab, setActiveTab] = useState<TabType>('live');
    const [selectedReport, setSelectedReport] = useState<Report | null>(null);
    const [logs, setLogs] = useState<LogEntry[]>([]);
    const [isPaused, setIsPaused] = useState(false);
    const logsEndRef = useRef<HTMLDivElement>(null);

    // Auto-scroll logs
    useEffect(() => {
        if (!isPaused && logsEndRef.current) {
            logsEndRef.current.scrollIntoView({ behavior: 'smooth' });
        }
    }, [logs, isPaused]);

    // Generate mock logs
    useEffect(() => {
        const interval = setInterval(() => {
            if (!isPaused) {
                const levels: LogEntry['level'][] = ['info', 'warning', 'critical', 'processing'];
                const messages = [
                    'Agent A024 completed data scraping',
                    'Satellite imagery analysis in progress',
                    'ALERT: High severity detected in sector 7',
                    'Resource allocation updated',
                    'IoT sensor anomaly detected',
                    'Report generation started',
                ];

                const newLog: LogEntry = {
                    id: `log-${Date.now()}`,
                    level: levels[Math.floor(Math.random() * levels.length)],
                    message: messages[Math.floor(Math.random() * messages.length)],
                    timestamp: Date.now(),
                };

                setLogs((prev) => [...prev.slice(-50), newLog]); // Keep last 50 logs
            }
        }, 2000);

        return () => clearInterval(interval);
    }, [isPaused]);

    const handleGenerateReport = () => {
        const newReport: Report = {
            id: `R${Date.now()}`,
            title: `Situation Report - ${new Date().toLocaleString()}`,
            content: `# Situation Report

## Executive Summary
Automated analysis of disaster response operations as of ${new Date().toLocaleString()}.

## Agent Status
- **Total Agents**: 100
- **Active Operations**: ${Math.floor(Math.random() * 50 + 20)}
- **Critical Alerts**: ${Math.floor(Math.random() * 5)}

## Disaster Assessment
${Math.floor(Math.random() * 3) + 1} active disaster zone(s) detected with varying severity levels.

### Resource Allocation
- Medical supplies: **Adequate**
- Emergency personnel: **Deployed**
- Shelter capacity: **${Math.floor(Math.random() * 100)}%**

## Recommendations
1. Continue monitoring high-risk zones
2. Increase resource allocation to sector ${Math.floor(Math.random() * 10) + 1}
3. Maintain current response protocols

---
*Generated by ResilienceGrid AI System*
`,
            timestamp: new Date().toISOString(),
            confidence: Math.random() * 30 + 70, // 70-100%
            affectedArea: `${Math.floor(Math.random() * 100)} km²`,
            critical: Math.random() > 0.7,
        };

        addReport(newReport);
        setSelectedReport(newReport);
    };

    const getLevelColor = (level: LogEntry['level']) => {
        switch (level) {
            case 'info':
                return 'text-text-secondary';
            case 'warning':
                return 'text-yellow-400';
            case 'critical':
                return 'text-red-400';
            case 'processing':
                return 'text-cyan-400';
        }
    };

    const displayedReports = activeTab === 'live' ? reports.slice(0, 5) : reports;

    return (
        <div className="h-full flex flex-col bg-eoc-surface rounded-lg border border-gray-800">
            {/* Header */}
            <div className="p-3 border-b border-gray-800 flex items-center justify-between">
                <h2 className="text-cyan-400 font-mono text-sm font-semibold uppercase tracking-wider">
                    Situation Reports
                </h2>
                <button
                    onClick={handleGenerateReport}
                    className="bg-green-600 hover:bg-green-700 text-white px-3 py-1.5 rounded 
            text-xs font-mono font-semibold transition-colors"
                >
                    Generate New
                </button>
            </div>

            {/* Tabs */}
            <div className="flex border-b border-gray-800">
                {(['live', 'archive', 'settings'] as TabType[]).map((tab) => (
                    <button
                        key={tab}
                        onClick={() => setActiveTab(tab)}
                        className={`flex-1 py-2 text-xs font-mono uppercase transition-colors ${activeTab === tab
                                ? 'bg-eoc-elevated text-cyan-400 border-b-2 border-cyan-400'
                                : 'text-text-secondary hover:bg-eoc-elevated/50'
                            }`}
                    >
                        {tab}
                    </button>
                ))}
            </div>

            {/* Report List */}
            <div className="flex-1 overflow-y-auto p-3 space-y-2">
                {displayedReports.length === 0 ? (
                    <div className="text-center text-text-secondary text-sm font-mono py-8">
                        No reports yet. Click "Generate New" to create one.
                    </div>
                ) : (
                    displayedReports.map((report) => (
                        <div
                            key={report.id}
                            onClick={() => setSelectedReport(report)}
                            className={`bg-eoc-elevated rounded-lg p-3 cursor-pointer transition-all hover:bg-gray-700 ${selectedReport?.id === report.id ? 'ring-2 ring-cyan-600' : ''
                                }`}
                        >
                            <div className="flex items-start justify-between mb-1">
                                <h3 className="text-text-primary text-sm font-mono font-bold line-clamp-1">
                                    {report.title}
                                </h3>
                                {report.critical && (
                                    <span className="bg-red-600 text-white text-[10px] font-mono px-1.5 py-0.5 rounded">
                                        CRITICAL
                                    </span>
                                )}
                            </div>

                            <div className="flex items-center gap-3 text-xs font-mono text-text-secondary mb-2">
                                <span>{new Date(report.timestamp).toLocaleTimeString()}</span>
                                {report.affectedArea && <span>Area: {report.affectedArea}</span>}
                            </div>

                            {/* Confidence Score */}
                            <div className="space-y-1">
                                <div className="flex justify-between text-xs font-mono">
                                    <span className="text-text-secondary">Confidence</span>
                                    <span className="text-text-primary font-semibold">
                                        {report.confidence.toFixed(1)}%
                                    </span>
                                </div>
                                <div className="w-full bg-gray-800 rounded-full h-1.5">
                                    <div
                                        className="bg-cyan-600 h-1.5 rounded-full transition-all"
                                        style={{ width: `${report.confidence}%` }}
                                    ></div>
                                </div>
                            </div>
                        </div>
                    ))
                )}
            </div>

            {/* Agent Activity Stream */}
            <div className="border-t border-gray-800 h-48 flex flex-col">
                <div className="p-2 bg-eoc-elevated flex items-center justify-between">
                    <span className="text-text-secondary text-xs font-mono font-semibold uppercase">
                        Agent Activity Stream
                    </span>
                    <button
                        onClick={() => setIsPaused(!isPaused)}
                        className={`text-xs font-mono px-2 py-1 rounded transition-colors ${isPaused ? 'bg-yellow-600 text-white' : 'bg-gray-700 text-text-secondary'
                            }`}
                    >
                        {isPaused ? 'PAUSED' : 'LIVE'}
                    </button>
                </div>

                <div
                    className="flex-1 overflow-y-auto p-2 bg-black/30 font-mono text-xs space-y-1"
                    onMouseEnter={() => setIsPaused(true)}
                    onMouseLeave={() => setIsPaused(false)}
                >
                    {logs.map((log) => (
                        <div key={log.id} className="flex items-start gap-2">
                            <span className="text-text-secondary text-[10px]">
                                {new Date(log.timestamp).toLocaleTimeString()}
                            </span>
                            <span className={`flex-1 ${getLevelColor(log.level)}`}>{log.message}</span>
                        </div>
                    ))}
                    <div ref={logsEndRef} />
                </div>
            </div>

            {/* Report Detail Modal (Simplified) */}
            {selectedReport && (
                <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-8">
                    <div className="bg-eoc-surface rounded-lg border border-gray-700 max-w-2xl w-full max-h-[80vh] overflow-hidden flex flex-col">
                        <div className="p-4 border-b border-gray-700 flex items-center justify-between">
                            <h2 className="text-text-primary font-mono text-lg font-bold">
                                {selectedReport.title}
                            </h2>
                            <button
                                onClick={() => setSelectedReport(null)}
                                className="text-text-secondary hover:text-text-primary text-2xl"
                            >
                                ×
                            </button>
                        </div>

                        <div className="flex-1 overflow-y-auto p-6">
                            <ReactMarkdown className="prose prose-invert max-w-none font-mono text-sm">
                                {selectedReport.content}
                            </ReactMarkdown>
                        </div>

                        <div className="p-4 border-t border-gray-700 flex gap-2">
                            <button className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded text-sm font-mono transition-colors">
                                Download PDF
                            </button>
                            <button className="bg-gray-700 hover:bg-gray-600 text-white px-4 py-2 rounded text-sm font-mono transition-colors">
                                Share
                            </button>
                            {!selectedReport.critical && (
                                <button className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded text-sm font-mono transition-colors ml-auto">
                                    Mark Critical
                                </button>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};
